test:
  clients:
    default:
      database: arkaan-rspec
      hosts:
        - ds215759.mlab.com:15759
      options:
        user: virtuatable
        password: Patate123!
        retry_writes: false