apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: "{{service}}-virtual-host-ingress"
  labels:
    app: "{{service}}"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - path: "/{{service}}(/|$)(.*)"
        backend:
          serviceName: "{{service}}-service"
          servicePort: {{port}}