apiVersion: v1
kind: Service
metadata:
  name: "{{service}}-service"
spec:
  selector:
    app: "{{service}}"
  ports:
    - protocol: TCP
      port: {{port}}
      targetPort: {{port}}
  type: ClusterIP